### PR TITLE
Add libvdwxc

### PR DESCRIPTION
**Pull request by gdonval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gdonval** [comment]
@conda-forge-admin, please rerender

**Comment by gdonval** [comment]
Note that I checked last week that `track_features` was still the recommended way to reduce variant priorities. As before my involvement, the openmpi variant was the only one provided, I chose to make it the default version too.

Alternatively, the `nompi` variant could be prioritized as it requires fewer dependencies but it makes little sense for a program like gpaw (and `mpiexec -n 1 gpaw ...` is definitely possible).

**Comment by gdonval** [comment]
Local openmpi and mpich versions built with this recipe are passing tests (full pytest suite, including libvdwxc, elpa and scalapack tests).

Ready to be merged.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
