### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Libxc 5.0.0 error: 

```
2020-05-28T13:23:16.9719783Z     In file included from c/xc/revtpss_c_pbe.c:6:0:
2020-05-28T13:23:16.9723124Z     c/xc/revtpss_c_pbe.c: In function 'xc_perdew_params':
2020-05-28T13:23:16.9726540Z     c/xc/revtpss_c_pbe.c:70:5: error: too few arguments to function 'xc_lda'
2020-05-28T13:23:16.9730889Z          XC(lda)(gga_p, np, rho, &(pt->ecunif), pt->vcunif, pt->fcunif, NULL);
2020-05-28T13:23:16.9734368Z          ^
2020-05-28T13:23:16.9738584Z     In file included from c/xc/revtpss_c_pbe.c:6:0:
2020-05-28T13:23:16.9743085Z     /home/conda/feedstock_root/build_artifacts/gpaw_1590671982878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include/xc.h:245:6: note: declared here
2020-05-28T13:23:16.9746387Z      void xc_lda (const xc_func_type *p, size_t np, const double *rho,
2020-05-28T13:23:16.9750099Z           ^~~~~~
2020-05-28T13:23:16.9821844Z     error: command '/home/conda/feedstock_root/build_artifacts/gpaw_1590671982878/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1
2020-05-28T13:23:17.0270687Z     Running setup.py install for gpaw: finished with status 'error'
```

**Comment by jan-janssen** [comment]
Compilation fails: 

```
2020-05-28T13:31:04.1825524Z     mpicc -o build/bin.linux-x86_64-3.6//gpaw-python build/temp.linux-x86_64-3.6/c/_gpaw.o build/temp.linux-x86_64-3.6/c/bc.o build/temp.linux-x86_64-3.6/c/blacs.o build/temp.linux-x86_64-3.6/c/blas.o build/temp.linux-x86_64-3.6/c/bmgs/bmgs.o build/temp.linux-x86_64-3.6/c/cerf.o build/temp.linux-x86_64-3.6/c/constraints.o build/temp.linux-x86_64-3.6/c/elpa.o build/temp.linux-x86_64-3.6/c/fftw.o build/temp.linux-x86_64-3.6/c/lapack.o build/temp.linux-x86_64-3.6/c/lcao.o build/temp.linux-x86_64-3.6/c/lfc.o build/temp.linux-x86_64-3.6/c/lfc2.o build/temp.linux-x86_64-3.6/c/localized_functions.o build/temp.linux-x86_64-3.6/c/mlsqr.o build/temp.linux-x86_64-3.6/c/mpi.o build/temp.linux-x86_64-3.6/c/operators.o build/temp.linux-x86_64-3.6/c/plane_wave.o build/temp.linux-x86_64-3.6/c/plt.o build/temp.linux-x86_64-3.6/c/point_charges.o build/temp.linux-x86_64-3.6/c/spline.o build/temp.linux-x86_64-3.6/c/symmetry.o build/temp.linux-x86_64-3.6/c/tetra.o build/temp.linux-x86_64-3.6/c/transformers.o build/temp.linux-x86_64-3.6/c/utilities.o build/temp.linux-x86_64-3.6/c/wigner_seitz.o build/temp.linux-x86_64-3.6/c/woperators.o build/temp.linux-x86_64-3.6/c/xc/ensemble_gga.o build/temp.linux-x86_64-3.6/c/xc/libvdwxc.o build/temp.linux-x86_64-3.6/c/xc/libxc.o build/temp.linux-x86_64-3.6/c/xc/m06l.o build/temp.linux-x86_64-3.6/c/xc/pbe.o build/temp.linux-x86_64-3.6/c/xc/pw91.o build/temp.linux-x86_64-3.6/c/xc/revtpss.o build/temp.linux-x86_64-3.6/c/xc/revtpss_c_pbe.o build/temp.linux-x86_64-3.6/c/xc/rpbe.o build/temp.linux-x86_64-3.6/c/xc/tpss.o build/temp.linux-x86_64-3.6/c/xc/vdw.o build/temp.linux-x86_64-3.6/c/xc/xc.o build/temp.linux-x86_64-3.6/c/xc/xc_mgga.o  -L/home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/config-3.6m-x86_64-linux-gnu -lxc -lblas -llapack -lscalapack -lfftw3 /home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libpython3.6m.a -lpthread -ldl  -lutil -lrt -lm  -Wl,-rpath=/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -L/home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -L/home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib     -Xlinker -export-dynamic
2020-05-28T13:31:04.3016187Z     lto1: fatal error: bytecode stream in file '/home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/libpython3.6m.a' generated with LTO version 6.0 instead of the expected 6.2
2020-05-28T13:31:04.3021056Z     compilation terminated.
2020-05-28T13:31:04.3029273Z     lto-wrapper: fatal error: /home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc returned 1 exit status
2020-05-28T13:31:04.3035902Z     compilation terminated.
2020-05-28T13:31:04.3043106Z     /home/conda/feedstock_root/build_artifacts/gpaw_1590672443146/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.5.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: error: lto-wrapper failed
2020-05-28T13:31:04.3049710Z     collect2: error: ld returned 1 exit status
2020-05-28T13:31:04.3055998Z     Traceback (most recent call last):
2020-05-28T13:31:04.3062528Z       File "<string>", line 1, in <module>
2020-05-28T13:31:04.3068077Z       File "/tmp/pip-req-build-zfc0ssv9/setup.py", line 281, in <module>
2020-05-28T13:31:04.3073611Z         'Topic :: Scientific/Engineering :: Physics'])
```

**Comment by bjodah** [comment]
@jan-janssen nice to see that you're keeping the ball rolling here. Unfortunately I won't be using gpaw in my new capacity at work, so you probably want to add yourself as a maintainer of this recipe as well.

**Comment by jan-janssen** [comment]
@bjodah Ok, let me try to get at least one version working again. I ping you once I have a working version.

**Comment by jan-janssen** [comment]
@bjodah If you have other material science related packages I might also be interested in take them over like https://github.com/conda-forge/libxc-feedstock/pull/5

**Comment by bjodah** [comment]
I think it's only those.:-)

**Pull request closed without merging**
