### PR TITLE
Add aarch64 gpaw build

### PR DESCRIPTION
**Pull request by gdonval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gdonval** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Should not we use https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt ? as explained in https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

**Comment by gdonval** [comment]
@conda-forge-admin, please restart ci

**Comment by gdonval** [comment]
@conda-forge-admin, please restart ci

**Comment by gdonval** [comment]
@conda-forge-admin, please rerender

**Comment by gdonval** [comment]
> Should not we use https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt ? as explained in https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

Sorry, your message got lost in the middle of all this. If I understood correctly, the osx migration thing will trigger PRs for the package and all its dependencies automatically. The current work is to enable `aarch64` specifically for Cavium ARM chips. 

OSX is coming next hopefully! And you are right, I'll use the migration thingy for it.

**Comment by gdonval** [comment]
@conda-forge-admin, please rerender

**Comment by gdonval** [comment]
@conda-forge-admin, please restart ci

**Comment by gdonval** [comment]
Fails now with:

```
creating build/lib.linux-aarch64-cpython-38
mpicc -pthread -B $PREFIX/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/gpaw-22.8.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include build/temp.linux-aarch64-cpython-38/c/_gpaw.o build/temp.linux-aarch64-cpython-38/c/bc.o build/temp.linux-aarch64-cpython-38/c/blacs.o build/temp.linux-aarch64-cpython-38/c/blas.o build/temp.linux-aarch64-cpython-38/c/bmgs/bmgs.o build/temp.linux-aarch64-cpython-38/c/constraints.o build/temp.linux-aarch64-cpython-38/c/elpa.o build/temp.linux-aarch64-cpython-38/c/fd_preconditioner.o build/temp.linux-aarch64-cpython-38/c/fftw.o build/temp.linux-aarch64-cpython-38/c/lcao.o build/temp.linux-aarch64-cpython-38/c/lfc.o build/temp.linux-aarch64-cpython-38/c/lfc2.o build/temp.linux-aarch64-cpython-38/c/mpi.o build/temp.linux-aarch64-cpython-38/c/operators.o build/temp.linux-aarch64-cpython-38/c/plane_wave.o build/temp.linux-aarch64-cpython-38/c/plt.o build/temp.linux-aarch64-cpython-38/c/point_charges.o build/temp.linux-aarch64-cpython-38/c/spline.o build/temp.linux-aarch64-cpython-38/c/symmetry.o build/temp.linux-aarch64-cpython-38/c/tetra.o build/temp.linux-aarch64-cpython-38/c/transformers.o build/temp.linux-aarch64-cpython-38/c/utilities.o build/temp.linux-aarch64-cpython-38/c/wigner_seitz.o build/temp.linux-aarch64-cpython-38/c/woperators.o build/temp.linux-aarch64-cpython-38/c/xc/ensemble_gga.o build/temp.linux-aarch64-cpython-38/c/xc/libvdwxc.o build/temp.linux-aarch64-cpython-38/c/xc/libxc.o build/temp.linux-aarch64-cpython-38/c/xc/m06l.o build/temp.linux-aarch64-cpython-38/c/xc/pbe.o build/temp.linux-aarch64-cpython-38/c/xc/pw91.o build/temp.linux-aarch64-cpython-38/c/xc/revtpss.o build/temp.linux-aarch64-cpython-38/c/xc/revtpss_c_pbe.o build/temp.linux-aarch64-cpython-38/c/xc/rpbe.o build/temp.linux-aarch64-cpython-38/c/xc/tpss.o build/temp.linux-aarch64-cpython-38/c/xc/vdw.o build/temp.linux-aarch64-cpython-38/c/xc/xc.o build/temp.linux-aarch64-cpython-38/c/xc/xc_mgga.o -lxc -lfftw3_omp -lfftw3 -lelpa_openmp -lelpa -lscalapack -lblas -llapack -lxc -lvdwxc -o build/lib.linux-aarch64-cpython-38/_gpaw.cpython-38-aarch64-linux-gnu.so -fopenmp -fopenmp-simd
/home/conda/feedstock_root/build_artifacts/gpaw_1665606886482/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/compiler_compat/ld: /home/conda/feedstock_root/build_artifacts/gpaw_1665606886482/_build_env/bin/../libexec/gcc/aarch64-conda-linux-gnu/10.4.0/liblto_plugin.so: error loading plugin: /home/conda/feedstock_root/build_artifacts/gpaw_1665606886482/_build_env/bin/../libexec/gcc/aarch64-conda-linux-gnu/10.4.0/liblto_plugin.so: cannot open shared object file: No such file or directory
collect2: error: ld returned 1 exit status
```

I'll have a look and sort it out tomorrow.

**Comment by gdonval** [comment]
@jan-janssen, could you check I have not done anything crazy and this should be good to go! Next step will be osx!

**Comment by jan-janssen** [comment]
Looks good to me

**Pull request merged**
